// <auto-generated />
using System;
using InventoryManagement.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InventoryManagement.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251104103443_changedtoGuid")]
    partial class changedtoGuid
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("InventoryManagement.Models.FullInventory", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<string>("InventoryId")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("customBoolName1")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("customBoolName2")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("customBoolName3")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("customBoolState1")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("customBoolState2")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("customBoolState3")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("customIntName1")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("customIntName2")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("customIntName3")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("customIntState1")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("customIntState2")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("customIntState3")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("customLinkName1")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("customLinkName2")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("customLinkName3")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("customLinkState1")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("customLinkState2")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("customLinkState3")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("customMultStringState1")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("customMultiStringName1")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("customMultiStringName2")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("customMultiStringName3")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("customMultiStringState2")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("customMultiStringState3")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("customSingleStringName1")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("customSingleStringName2")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("customSingleStringName3")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("customSingleStringState1")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("customSingleStringState2")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("customSingleStringState3")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("imageUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("isPublic")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("UserId", "InventoryId");

                    b.ToTable("FullInventories");
                });

            modelBuilder.Entity("InventoryManagement.Models.Inventory", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<string>("InventoryId")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("NumofItems")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("UserId", "InventoryId");

                    b.ToTable("Inventories");
                });

            modelBuilder.Entity("InventoryManagement.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("AuthProvider")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("InventoriesCreated")
                        .HasColumnType("int");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UserStatus")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("InventoryManagement.Models.FullInventory", b =>
                {
                    b.HasOne("InventoryManagement.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InventoryManagement.Models.Inventory", b =>
                {
                    b.HasOne("InventoryManagement.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
