// <auto-generated />
using System;
using InventoryManagement.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InventoryManagement.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251104113947_fixedmodelagain")]
    partial class fixedmodelagain
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("InventoryManagement.Models.FullInventory", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<string>("InventoryId")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CustomBoolName1")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("CustomBoolName2")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("CustomBoolName3")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("CustomBoolState1")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("CustomBoolState2")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("CustomBoolState3")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("CustomBoolValue1")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("CustomBoolValue2")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("CustomBoolValue3")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("CustomIntName1")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("CustomIntName2")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("CustomIntName3")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("CustomIntState1")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("CustomIntState2")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("CustomIntState3")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("CustomIntValue1")
                        .HasMaxLength(100)
                        .HasColumnType("int");

                    b.Property<int?>("CustomIntValue2")
                        .HasMaxLength(100)
                        .HasColumnType("int");

                    b.Property<int?>("CustomIntValue3")
                        .HasMaxLength(100)
                        .HasColumnType("int");

                    b.Property<string>("CustomLinkName1")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("CustomLinkName2")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("CustomLinkName3")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("CustomLinkState1")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("CustomLinkState2")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("CustomLinkState3")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("CustomLinkValue1")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("CustomLinkValue2")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("CustomLinkValue3")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("CustomMultStringState1")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("CustomMultiStringName1")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("CustomMultiStringName2")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("CustomMultiStringName3")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("CustomMultiStringState2")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("CustomMultiStringState3")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("CustomMultiStringValue1")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("CustomMultiStringValue2")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("CustomMultiStringValue3")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("CustomSingleStringName1")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("CustomSingleStringName2")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("CustomSingleStringName3")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("CustomSingleStringState1")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("CustomSingleStringState2")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("CustomSingleStringState3")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("CustomSingleStringValue1")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("CustomSingleStringValue2")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("CustomSingleStringValue3")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("UserId", "InventoryId");

                    b.ToTable("FullInventories");
                });

            modelBuilder.Entity("InventoryManagement.Models.Inventory", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<string>("InventoryId")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("NumofItems")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("UserId", "InventoryId");

                    b.ToTable("Inventories");
                });

            modelBuilder.Entity("InventoryManagement.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("AuthProvider")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("InventoriesCreated")
                        .HasColumnType("int");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UserStatus")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("InventoryManagement.Models.FullInventory", b =>
                {
                    b.HasOne("InventoryManagement.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InventoryManagement.Models.Inventory", b =>
                {
                    b.HasOne("InventoryManagement.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
